DATASET_ID: crmTrieste
PARAMETRI:
  iperparams:
    colsample_bytree: 0.5868323733872024
    eval_metric: [auc, logloss]
    gamma: 1.1060552077820258
    learning_rate: 0.1
    max_depth: 7
    min_child_weight: 8
    n_estimators: 499
    n_jobs: 3
    objective: binary:logistic
    reg_alpha: 0.560674658894005
    reg_lambda: 0.04109383840952241
    subsample: 0.6975732844651784
  max_evals: 50
  n_est_max: 1000
  space:
    colsample_bytree: !!python/object:hyperopt.pyll.base.Apply
      define_params: null
      name: float
      named_args: []
      o_len: null
      pos_args:
      - !!python/object:hyperopt.pyll.base.Apply
        define_params: null
        name: hyperopt_param
        named_args: []
        o_len: null
        pos_args:
        - !!python/object:hyperopt.pyll.base.Literal
          _obj: colsample_bytree
          define_params: null
          name: literal
          named_args: []
          o_len: 16
          pos_args: []
          pure: true
        - !!python/object:hyperopt.pyll.base.Apply
          define_params: null
          name: uniform
          named_args: []
          o_len: null
          pos_args:
          - !!python/object:hyperopt.pyll.base.Literal
            _obj: 0.4
            define_params: null
            name: literal
            named_args: []
            o_len: null
            pos_args: []
            pure: true
          - !!python/object:hyperopt.pyll.base.Literal
            _obj: 0.8
            define_params: null
            name: literal
            named_args: []
            o_len: null
            pos_args: []
            pure: true
          pure: false
        pure: false
      pure: true
    gamma: !!python/object:hyperopt.pyll.base.Apply
      define_params: null
      name: float
      named_args: []
      o_len: null
      pos_args:
      - !!python/object:hyperopt.pyll.base.Apply
        define_params: null
        name: hyperopt_param
        named_args: []
        o_len: null
        pos_args:
        - !!python/object:hyperopt.pyll.base.Literal
          _obj: gamma
          define_params: null
          name: literal
          named_args: []
          o_len: 5
          pos_args: []
          pure: true
        - !!python/object:hyperopt.pyll.base.Apply
          define_params: null
          name: uniform
          named_args: []
          o_len: null
          pos_args:
          - !!python/object:hyperopt.pyll.base.Literal
            _obj: 0
            define_params: null
            name: literal
            named_args: []
            o_len: null
            pos_args: []
            pure: true
          - !!python/object:hyperopt.pyll.base.Literal
            _obj: 20
            define_params: null
            name: literal
            named_args: []
            o_len: null
            pos_args: []
            pure: true
          pure: false
        pure: false
      pure: true
    max_depth: !!python/object:hyperopt.pyll.base.Apply
      define_params: null
      name: switch
      named_args: []
      o_len: null
      pos_args:
      - !!python/object:hyperopt.pyll.base.Apply
        define_params: null
        name: hyperopt_param
        named_args: []
        o_len: null
        pos_args:
        - !!python/object:hyperopt.pyll.base.Literal
          _obj: max_depth
          define_params: null
          name: literal
          named_args: []
          o_len: 9
          pos_args: []
          pure: true
        - !!python/object:hyperopt.pyll.base.Apply
          define_params: null
          name: randint
          named_args: []
          o_len: null
          pos_args:
          - !!python/object:hyperopt.pyll.base.Literal
            _obj: 8
            define_params: null
            name: literal
            named_args: []
            o_len: null
            pos_args: []
            pure: true
          pure: false
        pure: false
      - !!python/object:hyperopt.pyll.base.Literal
        _obj: 3
        define_params: null
        name: literal
        named_args: []
        o_len: null
        pos_args: []
        pure: true
      - !!python/object:hyperopt.pyll.base.Literal
        _obj: 4
        define_params: null
        name: literal
        named_args: []
        o_len: null
        pos_args: []
        pure: true
      - !!python/object:hyperopt.pyll.base.Literal
        _obj: 5
        define_params: null
        name: literal
        named_args: []
        o_len: null
        pos_args: []
        pure: true
      - !!python/object:hyperopt.pyll.base.Literal
        _obj: 6
        define_params: null
        name: literal
        named_args: []
        o_len: null
        pos_args: []
        pure: true
      - !!python/object:hyperopt.pyll.base.Literal
        _obj: 7
        define_params: null
        name: literal
        named_args: []
        o_len: null
        pos_args: []
        pure: true
      - !!python/object:hyperopt.pyll.base.Literal
        _obj: 8
        define_params: null
        name: literal
        named_args: []
        o_len: null
        pos_args: []
        pure: true
      - !!python/object:hyperopt.pyll.base.Literal
        _obj: 9
        define_params: null
        name: literal
        named_args: []
        o_len: null
        pos_args: []
        pure: true
      - !!python/object:hyperopt.pyll.base.Literal
        _obj: 10
        define_params: null
        name: literal
        named_args: []
        o_len: null
        pos_args: []
        pure: true
      pure: true
    min_child_weight: !!python/object:hyperopt.pyll.base.Apply
      define_params: null
      name: float
      named_args: []
      o_len: null
      pos_args:
      - !!python/object:hyperopt.pyll.base.Apply
        define_params: null
        name: hyperopt_param
        named_args: []
        o_len: null
        pos_args:
        - !!python/object:hyperopt.pyll.base.Literal
          _obj: min_child_weight
          define_params: null
          name: literal
          named_args: []
          o_len: 16
          pos_args: []
          pure: true
        - !!python/object:hyperopt.pyll.base.Apply
          define_params: null
          name: quniform
          named_args: []
          o_len: null
          pos_args:
          - !!python/object:hyperopt.pyll.base.Literal
            _obj: 1
            define_params: null
            name: literal
            named_args: []
            o_len: null
            pos_args: []
            pure: true
          - !!python/object:hyperopt.pyll.base.Literal
            _obj: 20
            define_params: null
            name: literal
            named_args: []
            o_len: null
            pos_args: []
            pure: true
          - !!python/object:hyperopt.pyll.base.Literal
            _obj: 2
            define_params: null
            name: literal
            named_args: []
            o_len: null
            pos_args: []
            pure: true
          pure: false
        pure: false
      pure: true
    reg_alpha: !!python/object:hyperopt.pyll.base.Apply
      define_params: null
      name: float
      named_args: []
      o_len: null
      pos_args:
      - !!python/object:hyperopt.pyll.base.Apply
        define_params: null
        name: hyperopt_param
        named_args: []
        o_len: null
        pos_args:
        - !!python/object:hyperopt.pyll.base.Literal
          _obj: x_reg_alpha
          define_params: null
          name: literal
          named_args: []
          o_len: 11
          pos_args: []
          pure: true
        - !!python/object:hyperopt.pyll.base.Apply
          define_params: null
          name: uniform
          named_args: []
          o_len: null
          pos_args:
          - !!python/object:hyperopt.pyll.base.Literal
            _obj: 0
            define_params: null
            name: literal
            named_args: []
            o_len: null
            pos_args: []
            pure: true
          - !!python/object:hyperopt.pyll.base.Literal
            _obj: 1
            define_params: null
            name: literal
            named_args: []
            o_len: null
            pos_args: []
            pure: true
          pure: false
        pure: false
      pure: true
    reg_lambda: !!python/object:hyperopt.pyll.base.Apply
      define_params: null
      name: float
      named_args: []
      o_len: null
      pos_args:
      - !!python/object:hyperopt.pyll.base.Apply
        define_params: null
        name: hyperopt_param
        named_args: []
        o_len: null
        pos_args:
        - !!python/object:hyperopt.pyll.base.Literal
          _obj: x_reg_lambda
          define_params: null
          name: literal
          named_args: []
          o_len: 12
          pos_args: []
          pure: true
        - !!python/object:hyperopt.pyll.base.Apply
          define_params: null
          name: uniform
          named_args: []
          o_len: null
          pos_args:
          - !!python/object:hyperopt.pyll.base.Literal
            _obj: 0
            define_params: null
            name: literal
            named_args: []
            o_len: null
            pos_args: []
            pure: true
          - !!python/object:hyperopt.pyll.base.Literal
            _obj: 1
            define_params: null
            name: literal
            named_args: []
            o_len: null
            pos_args: []
            pure: true
          pure: false
        pure: false
      pure: true
    subsample: !!python/object:hyperopt.pyll.base.Apply
      define_params: null
      name: float
      named_args: []
      o_len: null
      pos_args:
      - !!python/object:hyperopt.pyll.base.Apply
        define_params: null
        name: hyperopt_param
        named_args: []
        o_len: null
        pos_args:
        - !!python/object:hyperopt.pyll.base.Literal
          _obj: subsample
          define_params: null
          name: literal
          named_args: []
          o_len: 9
          pos_args: []
          pure: true
        - !!python/object:hyperopt.pyll.base.Apply
          define_params: null
          name: uniform
          named_args: []
          o_len: null
          pos_args:
          - !!python/object:hyperopt.pyll.base.Literal
            _obj: 0.4
            define_params: null
            name: literal
            named_args: []
            o_len: null
            pos_args: []
            pure: true
          - !!python/object:hyperopt.pyll.base.Literal
            _obj: 0.8
            define_params: null
            name: literal
            named_args: []
            o_len: null
            pos_args: []
            pure: true
          pure: false
        pure: false
      pure: true
  test_size: 0.2
  use_grid: false
  use_hyperopt: false
RISULTATI: {auc: 0.7994758255731461, logloss: 0.4509712985747403}
