DEPACK:
  cat:
    PROVINCIA:
      GO: 0.2135
      TS: 0.2473
      UD: 0.5393
  cont:
    ETA:
    - 2
    - 118
DIZ_ENCODE: !!python/object/apply:collections.defaultdict
  args:
  - !!python/name:builtins.dict ''
  dictitems:
    PROVINCIA:
      GO: 2
      TS: 1
      UD: 0
FEAT_INFO:
  FEATURE_CATEGORICHE:
  - PROVINCIA
  FEATURE_CONTINUE:
  - ETA
  KEYS:
  - CONT_ID
  - COD_FISCALE_P_IVA
  TARGET:
  - SESSO
FILEPATH: ..\data\proc\crmTrieste.csv
